### ISSUE TITLE
项目跑不起，是不是少传了类

### ISSUE THREAD

**Issue by Jaggerer** [openhkr/EasyUtAndroid#1]
![image](https://user-images.githubusercontent.com/15099576/27991980-0756128c-64bb-11e7-8110-c6ab96f1bbad.png)
没有找到这个类

**Comment by Jaggerer** [comment]
用kt写的..没注意

**Comment by YangHaoyi** [comment]
为了响应谷歌kt第一开发语言的号召，以及java8判空Optional特性对API要求过高的原因，对数据转换的判空采用了kotlin来编写。不得不说kt的代码确实比java要简洁许多。
